version: "3.7"
services:
    # AWS CLI
    asess:
        # TODO change bash command promp to something fancier (currently "bash-5.0.0$")
        container_name: aws-mfa
        image: awscli
        build: 
            context: ./awscli
        entrypoint: bash /home/aws/scripts/asess.sh
        volumes:
            - ${AWS_CONFIG_FOLDER:-~/.aws}:/home/aws/.aws
            - ./awscli:/home/aws/scripts # TODO Convert this into a script in the image, and not in this folder
            - ${CWD}:/home/files
        command: help
    helm:
        image: alpine/helm:3.0.2
        volumes:
            - ~/.kube:/root/.kube
            - ~/.helm:/root/.helm
            - ${FILES_ROOT:-.}:/apps
        command: --help
    stern:
        image: stern
        build: 
            context: ./stern
        volumes:
            - ~/.kube:/stern/.kube
            - ~/.helm:/stern/.helm
            - ${FILES_ROOT:-.}:/apps
        entrypoint: /stern/stern
    kubectl:
        image: bitnami/kubectl:1.17-debian-9
        entrypoint: kubectl
        command: --help
    kubens:
        container_name: kubens
        image: kubensctx
        build:
            context: ./kubensctx
        entrypoint: kubens
    kubectx:
        container_name: kubectx
        image: kubensctx
        build:
            context: ./kubensctx
        entrypoint: kubectx

# TODO: Finish script that turns the services into commands in the terminal